// Todas as strings da UI em Português do Brasil
export const S = {
  // ── App ──────────────────────────────────────────────────────────────────
  appName: 'Pet Health',
  appTagline: 'Mantenha seus pets saudáveis e felizes',

  // ── Geral ─────────────────────────────────────────────────────────────────
  save: 'Salvar',
  cancel: 'Cancelar',
  confirm: 'Confirmar',
  delete: 'Excluir',
  edit: 'Editar',
  remove: 'Remover',
  add: 'Adicionar',
  back: '← Voltar',
  loading: 'Carregando...',
  error: 'Erro',
  ok: 'OK',
  yes: 'Sim',
  no: 'Não',
  optional: 'opcional',
  notes: 'Observações',
  notesPlaceholder: 'Detalhes adicionais...',
  saveChanges: 'Salvar alterações',

  // ── Auth ──────────────────────────────────────────────────────────────────
  signIn: 'Entrar',
  signInHeading: 'Bem-vindo de volta',
  signInButton: 'Entrar',
  signOut: 'Sair',
  createAccount: 'Criar conta',
  noAccount: 'Não tem conta? Crie uma',
  hasAccount: 'Já tem conta? Entre',
  email: 'E-mail',
  emailPlaceholder: 'voce@exemplo.com',
  password: 'Senha',
  passwordPlaceholder: '••••••••',
  passwordHint: 'Mínimo 8 caracteres',
  confirmPassword: 'Confirmar senha',
  confirmPasswordPlaceholder: 'Repita sua senha',
  firstName: 'Nome *',
  firstNamePlaceholder: 'Ana',
  lastName: 'Sobrenome',
  lastNamePlaceholder: 'Silva',
  forgotPassword: 'Esqueci minha senha',
  signInFailed: 'Falha ao entrar',
  signInVerificationRequired: 'Verificação adicional necessária. Verifique seu e-mail.',

  // Registro
  verifyEmail: 'Verificar e-mail',
  verifyEmailTagline: (email: string) => `Digite o código que enviamos para ${email}`,
  verificationCode: 'Código de verificação',
  verificationCodePlaceholder: '123456',
  verifyButton: 'Verificar',
  resendCode: 'Reenviar código',
  verificationFailed: 'Não foi possível verificar. Verifique o código e tente novamente.',

  // Validações auth
  firstNameRequired: 'Nome é obrigatório',
  emailRequired: 'E-mail é obrigatório',
  emailInvalid: 'Digite um e-mail válido',
  passwordRequired: 'Senha é obrigatória',
  passwordMinLength: 'Mínimo 8 caracteres',
  passwordsNoMatch: 'As senhas não coincidem',

  // Esqueci senha
  forgotPasswordTitle: 'Redefinir senha',
  forgotPasswordTagline: 'Enviaremos um código para o seu e-mail',
  sendCode: 'Enviar código',
  newPassword: 'Nova senha',
  newPasswordPlaceholder: 'Mínimo 8 caracteres',
  resetPassword: 'Redefinir senha',
  resetPasswordSuccess: 'Senha redefinida com sucesso!',
  resetPasswordSuccessMessage: 'Sua senha foi alterada. Faça login com a nova senha.',
  resetCodeSent: 'Código enviado! Verifique seu e-mail.',

  // ── Tabs de navegação ─────────────────────────────────────────────────────
  tabPets: 'Pets',
  tabReminders: 'Lembretes',
  tabAppointments: 'Consultas',
  tabVets: 'Veterinários',

  // ── Pets ──────────────────────────────────────────────────────────────────
  myPets: 'Meus Pets',
  petProfile: 'Perfil do Pet',
  addPet: 'Adicionar Pet',
  editPet: 'Editar Pet',
  greeting: (name: string) => `Olá, ${name}! 👋`,
  petCount: (n: number) => `${n} pet${n !== 1 ? 's' : ''} cadastrado${n !== 1 ? 's' : ''}`,
  loadingPets: 'Carregando seus pets...',
  noPets: 'Nenhum pet ainda',
  noPetsHint: 'Toque em + para adicionar seu primeiro pet e começar a acompanhar a saúde dele.',
  petName: 'Nome *',
  petNamePlaceholder: 'Bolinha',
  petSpecies: 'Espécie *',
  petBreed: 'Raça',
  petBreedPlaceholder: 'Golden Retriever',
  petBirthdate: 'Data de nascimento',
  petBirthdatePlaceholder: 'Selecione a data',
  petPhoto: 'Adicionar foto',
  petPhotoChange: 'Alterar foto',
  photoSource: 'Escolher foto',
  photoSourceCamera: 'Câmera',
  photoSourceGallery: 'Galeria',
  photoSourceCancel: 'Cancelar',
  petNameRequired: 'Nome é obrigatório',
  petSaveError: 'Não foi possível salvar o pet.',
  removePet: 'Remover Pet',
  removePetConfirm: (name: string) => `Tem certeza que deseja remover ${name}? Esta ação não pode ser desfeita.`,
  removePetError: 'Não foi possível remover o pet. Tente novamente.',

  // Espécies
  speciesDog: 'Cachorro',
  speciesCat: 'Gato',
  speciesBird: 'Pássaro',
  speciesRabbit: 'Coelho',
  speciesFish: 'Peixe',
  speciesReptile: 'Réptil',
  speciesOther: 'Outro',

  // Detalhes do pet
  statWeight: 'Peso',
  statAge: 'Idade',
  statSpecies: 'Espécie',
  logWeight: 'Registrar Peso',
  logWeightPrompt: 'Peso atual em kg:',
  logWeightPlaceholder: 'Ex: 8.5',
  logWeightInvalid: 'Peso inválido',
  logWeightInvalidMessage: 'Digite um número positivo válido.',
  logWeightError: 'Não foi possível salvar o registro de peso.',
  viewHealthRecords: 'Ver Registros de Saúde',
  weightHistory: 'Histórico de Peso',
  noWeightData: 'Nenhum dado de peso ainda. Adicione a primeira entrada!',
  weightHistoryTitle: 'Histórico de Peso (kg)',
  petNotFound: 'Pet não encontrado.',

  // Idades
  ageMonths: (m: number) => `${m} ${m !== 1 ? 'meses' : 'mês'}`,
  ageYearsMonths: (y: number, m: number) =>
    `${y} ${y !== 1 ? 'anos' : 'ano'}${m > 0 ? ` e ${m} ${m !== 1 ? 'meses' : 'mês'}` : ''}`,
  ageShortMonths: (m: number) => `${m}m`,
  ageShortYearsMonths: (y: number, m: number) => `${y}a${m > 0 ? ` ${m}m` : ''}`,

  // ── Registros de Saúde ────────────────────────────────────────────────────
  healthRecords: (petName: string) => `Registros de ${petName}`,
  addRecord: 'Adicionar Registro',
  editRecord: 'Editar Registro',
  recordDetail: 'Detalhes do Registro',
  noRecords: 'Nenhum registro ainda',
  noRecordsHint: 'Toque em + para registrar uma vacina, consulta ou exame.',
  recordType: 'Tipo de registro',
  recordTitle: 'Título *',
  recordTitlePlaceholder: 'Vacina anual',
  recordDate: 'Data *',
  recordDatePlaceholder: 'Selecione a data',
  recordVet: 'Veterinário',
  recordVetPlaceholder: 'Dr. Silva',
  recordNotes: 'Observações',
  recordAttachments: 'Anexos',
  addAttachments: 'Adicionar anexos',
  addAttachmentsCount: (n: number) => `Adicionar anexos (${n} ${n !== 1 ? 'novos' : 'novo'})`,
  existingAttachments: 'Anexos existentes',
  recordTitleRequired: 'Título é obrigatório',
  recordDateRequired: 'Data é obrigatória',
  recordSaveError: 'Não foi possível salvar o registro.',
  deleteRecord: 'Excluir Registro',
  deleteRecordConfirm: 'Tem certeza que deseja excluir este registro de saúde?',
  deleteRecordError: 'Não foi possível excluir o registro.',

  // Tipos de registro
  typeVaccine: 'Vacina',
  typeConsultation: 'Consulta',
  typeExam: 'Exame',
  typeSurgery: 'Cirurgia',
  typeOther: 'Outro',

  // ── Lembretes ─────────────────────────────────────────────────────────────
  reminders: 'Lembretes',
  addReminder: 'Adicionar Lembrete',
  editReminder: 'Editar Lembrete',
  noReminders: 'Nenhum lembrete',
  noRemindersHint: 'Toque em + para criar um lembrete de vacina, medicamento ou consulta.',
  upcomingReminders: (n: number) => `Próximos (${n})`,
  completedReminders: 'Concluídos',
  overdue: '⚠ Atrasado · ',
  recurring: 'Recorrente',
  reminderType: 'Tipo',
  reminderTitle: 'Título *',
  reminderTitlePlaceholder: 'Vacina anual contra raiva',
  reminderPet: 'Pet *',
  reminderDateTime: 'Data e hora *',
  reminderDateTimePlaceholder: 'Selecione data e hora',
  reminderRecurring: 'Lembrete recorrente',
  reminderRepeatDays: 'Repetir a cada (dias)',
  reminderRepeatDaysPlaceholder: '30',
  setReminder: 'Definir Lembrete',
  reminderTitleRequired: 'Título é obrigatório',
  reminderPetRequired: 'Selecione um pet',
  reminderDateRequired: 'Data e hora são obrigatórias',
  reminderSaveError: 'Não foi possível salvar o lembrete.',
  reminderMarkDone: 'Marcar como concluído',
  reminderEdit: 'Editar',
  reminderDelete: 'Excluir',
  reminderDeleteError: 'Não foi possível excluir o lembrete.',
  reminderOptions: 'O que deseja fazer?',
  reminderSnooze: 'Adiar',
  snooze1h: '1 hora',
  snooze4h: '4 horas',
  snoozeTomorrow: 'Amanhã',
  snoozeNextWeek: 'Próxima semana',

  // Tipos de lembrete
  reminderTypeVaccine: 'Vacina',
  reminderTypeConsultation: 'Consulta',
  reminderTypeMedication: 'Medicamento',
  reminderTypeExam: 'Exame',
  reminderTypeOther: 'Outro',

  // ── Consultas ─────────────────────────────────────────────────────────────
  appointments: 'Consultas',
  newAppointment: 'Nova Consulta',
  editAppointment: 'Editar Consulta',
  appointmentsOnDate: (date: string) => `Consultas em ${date}`,
  upcomingAppointments: (n: number) => `Próximas (${n})`,
  noAppointmentsDay: 'Nenhuma consulta neste dia',
  noUpcomingAppointments: 'Nenhuma consulta próxima',
  noAppointmentsHint: 'Toque em + para agendar uma nova consulta.',
  clearDate: 'Limpar',
  appointmentTitle: 'Título *',
  appointmentTitlePlaceholder: 'Check-up anual',
  appointmentPet: 'Pet *',
  appointmentVet: 'Veterinário (opcional)',
  appointmentVetNone: 'Nenhum',
  appointmentDateTime: 'Data e hora *',
  appointmentDateTimePlaceholder: 'Selecione data e hora',
  appointmentLocation: 'Local',
  appointmentLocationPlaceholder: 'Clínica Vet Cidade, Sala 3',
  appointmentNotes: 'Observações',
  appointmentStatus: 'Status',
  scheduleAppointment: 'Agendar Consulta',
  appointmentTitleRequired: 'Título é obrigatório',
  appointmentPetRequired: 'Selecione um pet',
  appointmentDateRequired: 'Data e hora são obrigatórias',
  appointmentSaveError: 'Não foi possível salvar a consulta.',
  deleteAppointment: 'Excluir Consulta',
  deleteAppointmentConfirm: (title: string) => `Excluir "${title}"?`,
  deleteAppointmentError: 'Não foi possível excluir.',
  appointmentOptions: 'Opções',
  changeStatus: 'Alterar status',
  changeStatusCurrent: (status: string) => `Status atual: ${status}`,

  // Status de consulta
  statusScheduled: 'Agendada',
  statusCompleted: 'Concluída',
  statusCancelled: 'Cancelada',

  // ── Veterinários ──────────────────────────────────────────────────────────
  vets: 'Veterinários',
  vetProfile: 'Perfil do Veterinário',
  addVet: 'Adicionar Veterinário',
  editVet: 'Editar Veterinário',
  noVets: 'Nenhum veterinário cadastrado',
  noVetsHint: 'Toque em + para adicionar um veterinário ao seu registro.',
  vetName: 'Nome *',
  vetNamePlaceholder: 'Silva',
  vetClinic: 'Clínica',
  vetClinicPlaceholder: 'Hospital Animal Cidade',
  vetPhone: 'Telefone',
  vetPhonePlaceholder: '(11) 99999-9999',
  vetEmail: 'E-mail',
  vetEmailPlaceholder: 'dr.silva@clinica.com',
  vetSpecialty: 'Especialidade',
  vetSpecialtyPlaceholder: 'Pequenos Animais',
  vetNotes: 'Observações',
  vetNotesPlaceholder: 'Alguma observação...',
  vetNameRequired: 'Nome é obrigatório',
  vetEmailInvalid: 'Digite um e-mail válido',
  vetSaveError: 'Não foi possível salvar o veterinário.',
  removeVet: 'Remover Veterinário',
  removeVetConfirm: (name: string) => `Remover Dr. ${name} do seu registro?`,
  removeVetError: 'Não foi possível remover o veterinário.',
  vetClinicLabel: 'Clínica',
  vetPhoneLabel: 'Telefone',
  vetEmailLabel: 'E-mail',
  vetNotesLabel: 'Observações',

  // ── Perfil ────────────────────────────────────────────────────────────────
  profile: 'Perfil',
  profileName: 'Nome completo',
  profileNamePlaceholder: 'Seu nome',
  profilePhoto: 'Foto do perfil',
  profileSave: 'Salvar perfil',
  profileSaveSuccess: 'Perfil atualizado com sucesso!',
  profileSaveError: 'Não foi possível salvar o perfil.',
};
